services:
  # Backend API Service
  - type: web
    name: progress-lens-tracker-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: progress-lens-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://progress-lens-tracker.onrender.com

  # Frontend Service  
  - type: web
    name: progress-lens-tracker
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: progress-lens-db
    databaseName: progress_lens_tracker
    user: progress_lens_user
